### ISSUE TITLE
Internal Error: ListCommits Error

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [ossf/scorecard-action#784]
Stacktrace for job

```
2022/08/02 19:06:34 internal error: ListCommits:error during graphqlHandler.setup: internal error: githubv4.Query: non-200 OK status code: 502 Bad Gateway body: "{\n   \"data\": null,\n   \"errors\":[\n      {\n         \"message\":\"Something went wrong while executing your query. This may be the result of a timeout, or it could be a GitHub bug. Please include `07C0:9C24:5DFA35:AFE1D4:62E975AB` when reporting this issue.\"\n      }\n   ]\n}\n"
panic: internal error: ListCommits:error during graphqlHandler.setup: internal error: githubv4.Query: non-200 OK status code: 502 Bad Gateway body: "{\n   \"data\": null,\n   \"errors\":[\n      {\n         \"message\":\"Something went wrong while executing your query. This may be the result of a timeout, or it could be a GitHub bug. Please include `07C0:9C24:5DFA35:AFE1D4:62E975AB` when reporting this issue.\"\n      }\n   ]\n}\n"

goroutine 1 [running]:
log.Panic(0xc000687918, 0x1, 0x1)
	log/log.go:354 +0xae
github.com/ossf/scorecard/v4/cmd.rootCmd(0xc000456000)
	github.com/ossf/scorecard/v4/cmd/root.go:137 +0x7bf
github.com/ossf/scorecard/v4/cmd.New.func2(0xc000449400, 0xc00044e3c0, 0x0, 0x6)
	github.com/ossf/scorecard/v4/cmd/root.go:61 +0x2a
github.com/spf13/cobra.(*Command).execute(0xc000449400, 0xc000030080, 0x6, 0x6, 0xc000449400, 0xc000030080)
	github.com/spf13/cobra@v1.4.0/command.go:860 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xc000449400, 0xc000449400, 0x41ab01, 0x0)
	github.com/spf13/cobra@v1.4.0/command.go:974 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.4.0/command.go:902
main.main()
	github.com/ossf/scorecard/v4/main.go:27 +0x39
```

- [link](https://github.com/pyhoneybot/honeybot/runs/7638564329?check_suite_focus=true)

**Comment by azeemshaikh38** [comment]
This gets fixed in the latest version of Scorecard - v2.0.0-beta.1. I sent out a PR to fix the issue and also added a Scorecard badge for the repo. Thanks :)
